title:            TOMOYUKI KASHIRO
description:      Front-end Engineer Tomoyuki Kashiro's blog
disqus_shortname: disqus
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: //blog.tomoyukikashiro.me

# Owner/author information
owner:
  name:           Tomoyuki Kashiro
  avatar:         avatar.png
  bio:            "while(true){ [HTML5, CSS3, JavaScript, Ruby].join('').hack(); }"
  email:          ksrtmyk@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Tkashiro
  facebook:       
  github:         kashiro
  stackexchange:  
  linkedin:       tomoyukikashiro
  instagram:      
  flickr:         
  tumblr:  
  resume:         http://tomoyukikashiro.me/resume      
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +KashiroTomoyuki

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-50867411-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Tokyo
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /post/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
